# Generated by Django 6.0.3 on 2026-03-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_of_service', models.CharField(max_length=64)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('sample_image', models.ImageField(blank=True, null=True, upload_to='services/')),
            ],
        ),
    ]
